# Site settings
title: Charles Ashby's blog
email: 
description: "Deep Learning Blog"
baseurl: ""
url: "http://charlesashby.github.io"
twitter_username: 
github_username:  charlesashby

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
